#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Prevent commits to the main branch.
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $current_branch = 'main' ]]
then
  echo "Do not commit directly to the main branch!"
  exit 1
fi

# Lint all staged files.
echo "Linting staged files..."
yarn lint-staged

